# Generated by Django 3.2.25 on 2024-11-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_client_digital_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='client/government_proofs/')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='government_proof',
        ),
        migrations.AddField(
            model_name='client',
            name='government_proofs',
            field=models.ManyToManyField(blank=True, related_name='government_proofs', to='client.FileModel'),
        ),
        migrations.AddField(
            model_name='client',
            name='property_proofs',
            field=models.ManyToManyField(blank=True, related_name='property_proofs', to='client.FileModel'),
        ),
    ]
