# Generated by Django 3.2.25 on 2024-11-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='year_of_experience',
            field=models.DecimalField(decimal_places=1, default=1.4, max_digits=10),
            preserve_default=False,
        ),
    ]
