# Generated by Django 3.2.25 on 2024-11-30 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20241130_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMeetingClientDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('scheduled_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('generated_teams_link', models.URLField(blank=True, null=True)),
                ('team_lead_response', models.CharField(choices=[('Yes', 'Yes'), ('Maybe', 'Maybe'), ('No', 'No')], default='No Response', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='project.project')),
            ],
        ),
    ]
