# Generated by Django 3.2.25 on 2024-12-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20241202_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmeetingclientdb',
            name='is_attending',
            field=models.BooleanField(default=False),
        ),
    ]
