# Generated by Django 3.2.25 on 2024-12-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20241202_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmeetingclientdb',
            name='meeting_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
