# Generated by Django 3.2.25 on 2024-12-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_projectmeetingclientdb_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmeetingclientdb',
            name='meeting_id',
            field=models.CharField(max_length=12),
        ),
    ]
