# Generated by Django 3.2.25 on 2024-12-02 10:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_phone_number'),
        ('project', '0012_alter_projectmeetingclientdb_meeting_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMeetingDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('client_email', models.EmailField(max_length=254)),
                ('team_lead_email', models.EmailField(max_length=254)),
                ('schedule_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('meeting_link', models.URLField(max_length=500)),
                ('meeting_password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='project.project')),
                ('team_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_meetings', to='employee.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectMeetingClientDB',
        ),
    ]
