# Generated by Django 3.2.25 on 2024-12-02 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20241202_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmeetingdb',
            name='team_lead',
        ),
    ]
