# Generated by Django 3.2.25 on 2024-12-02 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_remove_projectmeetingdb_team_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMeet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('meeting_password', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('scheduled_at', models.DateTimeField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Processed', 'Processed'), ('Canceled', 'Canceled')], default='Scheduled', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_meetings', to='project.project')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectMeetingDB',
        ),
    ]
